#!/bin/sh
#
# @name Gazebo Boat
# @type Boat
# @class Rover
#

. ${R}etc/init.d/rc.boat_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=boat}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=boat}
PX4_GZ_FOLLOW=${PX4_GZ_FOLLOW:=1}
PX4_GZ_FOLLOW_OFFSET_X=${PX4_GZ_FOLLOW_OFFSET_X:--4.0}
PX4_GZ_FOLLOW_OFFSET_Y=${PX4_GZ_FOLLOW_OFFSET_Y:--3.0}
PX4_GZ_FOLLOW_OFFSET_Z=${PX4_GZ_FOLLOW_OFFSET_Z:-2.0}

param set-default SIM_GZ_EN 1

# Propeller uses the wheel output path because it supports signed thrust.
param set SIM_GZ_WH_FUNC1 101
param set SIM_GZ_WH_MIN1 0
param set SIM_GZ_WH_MAX1 200
param set SIM_GZ_WH_DIS1 100

param set SIM_GZ_WH_FUNC2 102
param set SIM_GZ_WH_MIN2 0
param set SIM_GZ_WH_MAX2 200
param set SIM_GZ_WH_DIS2 100

# The Gazebo wheel bridge subtracts 100 from each wheel output before publishing
# motor_speed, so 100 is neutral, >100 is forward, and <100 is reverse.
# Stage-1 SDF drives both propellers from Motor1 for a straight-thrust baseline.
# Steering remains intentionally disabled until this baseline is stable.
param set CA_AIRFRAME 9
param set CA_ROTOR_COUNT 2
param set CA_ROTOR0_AX 1
param set CA_ROTOR0_AZ 0
param set CA_ROTOR0_KM 0
param set CA_ROTOR0_PX -3.7
param set CA_ROTOR0_PY -0.9
param set CA_ROTOR0_PZ -0.15
param set CA_ROTOR1_AX 1
param set CA_ROTOR1_AZ 0
param set CA_ROTOR1_KM 0
param set CA_ROTOR1_PX -3.7
param set CA_ROTOR1_PY 0.9
param set CA_ROTOR1_PZ -0.15
param set CA_R_REV 3

param set-default NAV_ACC_RAD 2
param set-default BOAT_LOOKAHD 5.0
param set-default BOAT_START_DIST 20.0
