#!/bin/sh
#
# @name Gazebo Boat
# @type Boat
# @class Rover
#

. ${R}etc/init.d/rc.boat_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=boat}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=boat}
PX4_GZ_FOLLOW=${PX4_GZ_FOLLOW:=1}
PX4_GZ_FOLLOW_OFFSET_X=${PX4_GZ_FOLLOW_OFFSET_X:--4.0}
PX4_GZ_FOLLOW_OFFSET_Y=${PX4_GZ_FOLLOW_OFFSET_Y:--3.0}
PX4_GZ_FOLLOW_OFFSET_Z=${PX4_GZ_FOLLOW_OFFSET_Z:-2.0}

param set-default SIM_GZ_EN 1

# Propeller uses the wheel output path because it supports signed thrust.
param set-default SIM_GZ_WH_FUNC1 101
param set-default SIM_GZ_WH_MIN1 0
param set-default SIM_GZ_WH_MAX1 200
param set-default SIM_GZ_WH_DIS1 100

# Rudder servo.
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_MAXA1 30
param set-default SIM_GZ_SV_MINA1 -30
param set-default SIM_GZ_SV_REV 0

# Single motor and single steering surface for the temporary SDF model.
param set-default CA_AIRFRAME 9
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX -0.9
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ -0.15
param set-default CA_R_REV 1
param set-default CA_SV_CS_COUNT 1

param set-default NAV_ACC_RAD 2
param set-default BOAT_LOOKAHD 5.0
param set-default BOAT_START_DIST 20.0
